### PR TITLE
Logomark

### PR DESCRIPTION
**Pull request by jksf**
Initial proposition for Logo

### CODE REVIEW

**Comment by biern** [comment]
👍 maybe let's just discuss it verbally

**Comment by biern** [comment]
Btw, what's this fonts name and how could I get it?

**Comment by jksf** [comment]
Comparison of logomarks:
https://github.com/SignHash/signhash-graphics/pull/1/commits/4ceea688fb4b5414ce0419cb4d1a2c3683f53547

**Comment by biern** [comment]
I appreciate the work on the logos!
IMOs:
- the blue, specially the lighter one has a very lightweight feel and I feel it contracts with the font and the symbol a lot, it's not as consistent as the grey one.
- I'm not bought on the 3D effect yet, maybe it's too deep, maybe it's just the colors.
- The inverse blue logotype looks very good! I think it could be further enhanced by adding the closed (/ open?) padlock on the left of the `SIGN` 

So, generally my feel is that darker colors suite that symbolic more than the light ones. But that's just my point of view of course :) I'll try to experiment on my own and suggest something as well

**Comment by jksf** [comment]
Sure, I am open to suggestions.
If you want to experiment use `make` to build PNGs. Before committing run `make clean all` to be sure.

I use Inkscape v0.92.1 r15371.

**Comment by jksf** [comment]
Changed logomark colors as we discussed recently. Also removed logotype for now so we can accept this PR and move on.

**Pull request merged**
